server:
  port: 8082
dubbo:
  zk:
    default:
      address: 127.0.0.1:2181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/day-study?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver